trainer:
  logger: true
  max_epochs: 100
  accelerator: 'gpu'
  devices: 1
  auto_select_gpus: True
  default_root_dir: './Exp/Polyp/FPN-PVT/'
  callbacks:
    class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      patience: 10
    class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      monitor: "dice"
      filename: "{epoch:02d}-{dice:.4f}"
      save_top_k: 1 
      mode: "max"

model: 
  learning_rate: 0.0001
  model_name: "UNet"

data:
  dataset_name: Polyp
  dataset_dir: /nvme/suyanzhou/dataset/dataset_2d/
  data_info_dir: /nvme/suyanzhou/dataset/data_infos/
  batch_size: 16
  image_size: 352
  num_workers: 16
